application:
  name: 'go-api-server-example'
  environment: 'production'

server:
  port: 8080

github:
  github_url: "https://api.github.com"
  github_token: ''

team_name:
  - name: mcereal
    channel: DEFAULT_CHANNEL_WEBHOOK_URL
    channel_type: slack
    enable_cron: true
    cron_elapsed_duration: 14400000000000 #4 Hours
    org:  "mcereal"
    ignore_users: 
    # - conveyor
    repos:
    - "botty"
