application:
  name: 'go-api-server-example'
  environment: 'production'

server:
  port: 8080

github:
  github_url: "https://github.com/api/v3"
  github_token: ''

team_name:
  - name: ops
    channel: DEFAULT_CHANNEL_WEBHOOK_URL
    enable_cron: true
    ignore_users: 
    # - conveyor
    repos:
    - "go-api-server-example"
    # - "cs-infra"
    # - "operations"
    # - "cs-apps"
    # - "bluefringe-infra"
