apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cs-code-review-bot
  namespace: cloud-systems-tools
spec:
  schedule: "0 * * * *"
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        cirrus.ibm.com/quotas: q256mb
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: cs-code-review-bot
              image: registry.cirrus.ibm.com/cloud-systems-tools/cs-code-review-bot:<tag>
              envFrom:
                - secretRef:
                    name: cs-code-review-bot
              resources: {}
              imagePullPolicy: Always
          imagePullSecrets:
            - name: mtos-quay
          restartPolicy: Never
          concurrencyPolicy: Forbid
          startingDeadlineSeconds: 200