name: build
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Security Scan
      uses: securego/gosec@master
      with:
        # we let the report trigger content trigger a failure using the GitHub Security features.
        args: '-no-fail -fmt sarif -out results.sarif ./...'

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif

    - name: set-up-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: make-output-directory
      run: mkdir output

    - name: test
      run: go test -v ./... -json > output/test-report.out

    - name: cover
      run: |
        go test -race -coverpkg $(go list ./... | grep -v generated | tr '\n' ',') -coverprofile output/cover.out ./...
        go tool cover -func=output/cover.out | grep total
        go tool cover --html=output/cover.out -o output/coverage.html
    - name: vet
      run: |
        go vet ./... > output/vet.out
    - name: revive
      run: |
        go install github.com/mgechev/revive@latest
        revive -exclude generated.go -exclude models_gen.go --exclude schema.resolvers.go -formatter default ./... > output/revive.out
    - name: sonar-cloud-scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
